trigger: none

pr:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'

  - script: dotnet workload install maui
    displayName: 'Install MAUI workload'

  - script: dotnet restore OneActivity.sln
    displayName: 'Restore dependencies'

  - script: dotnet build OneActivity.sln -c $(buildConfiguration) --no-restore
    displayName: 'Build solution'

  - script: dotnet test OneActivity.sln -c $(buildConfiguration) --no-build
    displayName: 'Run tests'
