version: "3.8"
services:
  azp-agent:
    build: .
    # For Apple Silicon you can force:
    # platform: linux/arm64/v8
    # For Intel Macs:
    # platform: linux/amd64
    environment:
      AZP_URL: "https://dev.azure.com/<your-org>"
      AZP_TOKEN: "<your-PAT>"
      AZP_POOL: "MacDockerPool"   # or "Default"
      AZP_AGENT_NAME: "macbook-docker"
      AZP_WORK: "_work"
      # Optional: pin a different agent version
      # AGENT_VERSION: "3.249.1"
    volumes:
      - azpwork:/azp/_work
    restart: unless-stopped
volumes:
  azpwork: {}