# Manual-only, per-app pipeline
trigger: none
pr: none

pool:
  vmImage: 'macOS-latest'

# ---------- REQUIRED runtime parameters ----------
parameters:
- name: displayVersion
  type: string
- name: track
  type: string
  values: [internal, alpha, beta, production]
- name: notesDir
  type: string
  default: ''

# ---------- Variables ----------
variables:
# Variable Group must contain: ANDROID_KEY_ALIAS, ANDROID_STORE_PASS, ANDROID_KEY_PASS
- group: maui-android

# App-specific constants
- name: ApplicationId
  value: com.softwarecowboys.onepushup
- name: MauiProject
  value: OneActivity.App.Pushups/OneActivity.App.Pushups.csproj
- name: KeystoreSecureFileName
  value: myapp.keystore
- name: BuildConfiguration
  value: Release
- name: TargetFramework
  value: net9.0-android
# Seed should be (last Play versionCode + 1)
- name: VersionCode
  value: $[counter('android-onepushup', 2)]

stages:
# ===========================
# Stage: Build
# ===========================
- stage: Build
  displayName: Build AAB
  jobs:
  # --- Validate run-time parameters ---
  - job: ValidateInputs
    displayName: Validate required parameters
    steps:
      - bash: |
          echo "Validating parameters..."
          DV='${{ parameters.displayVersion }}'
          TRACK='${{ parameters.track }}'
          if [ -z "$DV" ]; then
            echo "##vso[task.logissue type=error]Parameter 'displayVersion' is required."
            exit 1
          fi
          if ! echo "$DV" | grep -Eq '^[0-9]+(\.[0-9]+){1,2}([+-][0-9A-Za-z.-]+)?$'; then
            echo "##vso[task.logissue type=error]displayVersion '$DV' must look like 1.2 or 1.2.3 or 1.2.3-beta."
            exit 1
          fi
          if [ -z "$TRACK" ]; then
            echo "##vso[task.logissue type=error]Parameter 'track' is required."
            exit 1
          fi
          echo "OK."
        displayName: 'Fail early if params missing/invalid'

  # --- Validate the keystore file + store password + alias ---
  - job: ValidateKeystore
    dependsOn: ValidateInputs
    displayName: Validate keystore & alias
    steps:
      - task: DownloadSecureFile@1
        name: keystore
        inputs:
          secureFile: $(KeystoreSecureFileName)

      - bash: |
          set -euo pipefail
          echo "Keystore path: $(keystore.secureFilePath)"
          ls -l "$(keystore.secureFilePath)"

          echo "Checking STORE password..."
          if ! keytool -list -keystore "$(keystore.secureFilePath)" -storepass "$ANDROID_STORE_PASS" > /dev/null 2>&1; then
            echo "##vso[task.logissue type=error]Keystore store password is incorrect (ANDROID_STORE_PASS)."
            exit 1
          fi
          echo "Store password OK."

          echo "Collecting aliases..."
          ALIASES=$(keytool -list -keystore "$(keystore.secureFilePath)" -storepass "$ANDROID_STORE_PASS" 2>/dev/null | sed -n 's/^[[:space:]]*\([^,][^,]*\),.*/\1/p')
          echo "Found aliases: $ALIASES"
          MATCH=0
          for A in $ALIASES; do [ "$A" = "$ANDROID_KEY_ALIAS" ] && MATCH=1; done
          if [ $MATCH -ne 1 ]; then
            echo "##vso[task.logissue type=error]Alias '$ANDROID_KEY_ALIAS' not found in keystore."
            exit 1
          fi
          echo "Alias exists."
        displayName: 'Validate keystore + alias'
        env:
          ANDROID_STORE_PASS: $(ANDROID_STORE_PASS)
          ANDROID_KEY_ALIAS:  $(ANDROID_KEY_ALIAS)

  # --- Validate key password for the alias ---
  - job: ValidateKeyPassword
    dependsOn: ValidateKeystore
    displayName: Validate key password (alias)
    steps:
      - task: DownloadSecureFile@1
        name: keystore
        inputs:
          secureFile: $(KeystoreSecureFileName)

      - bash: |
          set -euo pipefail
          echo "Checking KEY password for alias '$ANDROID_KEY_ALIAS'..."
          if ! keytool -list -keystore "$(keystore.secureFilePath)" -storepass "$ANDROID_STORE_PASS" -alias "$ANDROID_KEY_ALIAS" -keypass "$ANDROID_KEY_PASS" > /dev/null 2>&1; then
            echo "##vso[task.logissue type=error]Key password is incorrect (ANDROID_KEY_PASS)."
            exit 1
          fi
          echo "Key password OK."
        displayName: 'Validate key password'
        env:
          ANDROID_STORE_PASS: $(ANDROID_STORE_PASS)
          ANDROID_KEY_PASS:  $(ANDROID_KEY_PASS)
          ANDROID_KEY_ALIAS: $(ANDROID_KEY_ALIAS)

  # --- Build (MSBuild signing) & publish artifact ---
  - job: BuildAndroid
    dependsOn: ValidateKeyPassword
    displayName: Build Android (MSBuild-signed)
    steps:
      - checkout: self
        clean: true

      - task: UseDotNet@2
        displayName: 'Use .NET 9 SDK'
        inputs:
          packageType: sdk
          version: 9.x

      # Install required workloads explicitly (reliable on macOS images)
      - bash: |
          set -e
          dotnet workload update || true
          dotnet workload install android ios maccatalyst maui
          dotnet workload list
        displayName: 'Install MAUI workloads (android/ios/maccatalyst/maui)'

      - bash: dotnet restore $(MauiProject)
        displayName: 'NuGet restore (MAUI project only)'

      - task: DownloadSecureFile@1
        name: keystore
        inputs:
          secureFile: $(KeystoreSecureFileName)

      # Publish to a fixed staging directory and SIGN via MSBuild properties (same as your local command)
      - bash: |
          set -euo pipefail
          OUT_DIR="$(Build.ArtifactStagingDirectory)/android"
          mkdir -p "$OUT_DIR"
          echo "Publishing (MSBuild signing) to $OUT_DIR"
          dotnet publish $(MauiProject) \
            -c $(BuildConfiguration) -f $(TargetFramework) \
            -o "$OUT_DIR" \
            /p:ApplicationVersion=$(VersionCode) \
            /p:ApplicationDisplayVersion=${{ parameters.displayVersion }} \
            /p:AndroidKeyStore=true \
            /p:AndroidSigningKeyStore="$(keystore.secureFilePath)" \
            /p:AndroidSigningStorePass="$(ANDROID_STORE_PASS)" \
            /p:AndroidSigningKeyAlias="$(ANDROID_KEY_ALIAS)" \
            /p:AndroidSigningKeyPass="$(ANDROID_KEY_PASS)" \
            /p:AndroidPackageFormats=aab \
            /bl:$(Build.SourcesDirectory)/maui.publish.binlog

          echo "Contents of $OUT_DIR:"
          ls -la "$OUT_DIR"
        displayName: 'Publish AAB (MSBuild-signed, with binlog)'
        env:
          ANDROID_STORE_PASS: $(ANDROID_STORE_PASS)
          ANDROID_KEY_PASS:  $(ANDROID_KEY_PASS)
          ANDROID_KEY_ALIAS: $(ANDROID_KEY_ALIAS)

      # Find the AAB deterministically (staging dir first, then safe fallback)
      - bash: |
          set -euo pipefail
          OUT_DIR="$(Build.ArtifactStagingDirectory)/android"
          echo "Looking for .aab in $OUT_DIR"
          AAB=$(find "$OUT_DIR" -maxdepth 2 -type f -name "*.aab" -print -quit || true)

          if [ -z "$AAB" ]; then
            echo "No .aab in $OUT_DIR. Showing OUT_DIR files:"
            find "$OUT_DIR" -maxdepth 2 -type f -print || true

            echo "Falling back to bin path search (excluding obj):"
            AAB=$(find "$(System.DefaultWorkingDirectory)" -type f -name "*.aab" -path "*/bin/*" ! -path "*/obj/*" -print -quit || true)
          fi

          if [ -z "$AAB" ]; then
            echo "##vso[task.logissue type=error]No .aab produced. See binlog artifact."
            exit 1
          fi

          # Stage to a deterministic upload filename
          UPLOAD_DIR="$(Build.ArtifactStagingDirectory)/upload"
          mkdir -p "$UPLOAD_DIR"
          DEST="$UPLOAD_DIR/$(ApplicationId).aab"
          cp -f "$AAB" "$DEST"

          echo "##vso[task.setvariable variable=UPLOAD_AAB;isOutput=true]$DEST"
          echo "Prepared upload bundle at: $DEST"
        name: prepupload
        displayName: 'Stage signed AAB'

      # Verify signature (READ-ONLY) and print SHA-1 from inside the bundle for sanity
      - bash: |
          set -euo pipefail
          echo "Verifying signature of $(prepupload.UPLOAD_AAB)..."
          jarsigner -verify -verbose -certs "$(prepupload.UPLOAD_AAB)"
          echo "Verification OK."
          echo "Certificate SHA1(s) found inside the AAB:"
          jarsigner -verify -verbose -certs "$(prepupload.UPLOAD_AAB)" | awk '/SHA1/{print}'
        displayName: 'Verify AAB signature (inspect certs)'

      # Publish artifacts (AAB + binlog for troubleshooting)
      - task: PublishBuildArtifacts@1
        displayName: 'Publish AAB artifact'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/upload'
          ArtifactName: 'aab'
          publishLocation: 'Container'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish binlog (always)'
        condition: always()
        inputs:
          PathtoPublish: '$(Build.SourcesDirectory)/maui.publish.binlog'
          ArtifactName: 'logs'
          publishLocation: 'Container'

# ===========================
# Stage: Release
# ===========================
- stage: Release
  displayName: Release to Google Play
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: PushToPlay
    displayName: Upload to Google Play
    steps:
      - download: current
        artifact: aab

      - task: GooglePlayRelease@4
        displayName: 'Upload to Google Play (${{ parameters.track }})'
        inputs:
          serviceConnection: 'googleplay-connection'    # your Google Play service connection name
          action: 'SingleBundle'
          applicationId: '$(ApplicationId)'
          bundleFile: '$(Pipeline.Workspace)/aab/$(ApplicationId).aab'   # exact staged file
          track: '${{ parameters.track }}'              # internal/alpha/beta/production
          userFraction: '0.1'
          whatsNewDirectory: '${{ parameters.notesDir }}'